version: "3.3"

services:
  whoami:
    image: "traefik/whoami" 
    networks: 
      web: 
      
    deploy:
      mode: replicated 
      replicas: 1
      labels:  
        - "traefik.enable=true"
        - 'traefik.docker.network=web'
        - "traefik.http.routers.who.rule=PathPrefix(`/who`)"
        - "traefik.http.services.who.loadbalancer.server.port=80"
        - "traefik.http.services.who.loadBalancer.sticky.cookie=true"
        - "traefik.http.services.who.loadBalancer.sticky.cookie.name=who"
        - "traefik.http.routers.who.entrypoints=https"
        - "traefik.http.routers.who.tls.certresolver=myresolver"
networks: 
  web:
    external: true