version: "3.7"
services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: . 
    volumes:
      - homer-data:/www/assets
    ports:
      - 42069:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
    deploy:  
      replicas: 1 
      placement:
        constraints:
          - node.labels.tipo == wickyflix
volumes:
  homer-data: