version: '3.8'

services: 
  db:
    image: hypriot/rpi-mysql
    volumes:
      - db_data:/var/lib/mysql
    deploy: 
      replicas: 1
      placement:
        constraints:
          - node.role==manager 
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root}
      MYSQL_DATABASE: ${mysql_database}
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_passwd}
    networks:
      - web  
  
  wordpress:
    image: wordpress:latest # can you place this if you want to use you own custom wp image  
    
    volumes:
      - /home/akira/WWW:/var/www/html
    deploy: 
      replicas: ${nodes_number}
      placement:
        constraints:
          - node.role==worker  
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=web'
        - "traefik.http.routers.wordpress.rule=PathPrefix(`/`)" 
        - "traefik.http.routers.wordpress.middlewares=wordpress-mw"
        - "traefik.http.middlewares.wordpress-mw.stripprefix.prefixes=/wordpress"
        - "traefik.http.routers.wordpress.service=wordpress" 
        - "traefik.http.routers.wordpress.entrypoints=https"
        - "traefik.http.routers.wordpress.tls.certresolver=myresolver"
        - "traefik.http.services.wordpress.loadbalancer.server.port=80"
        - "traefik.http.services.wordpress.loadBalancer.sticky.cookie=true"
        - "traefik.http.services.wordpress.loadBalancer.sticky.cookie.name=wordpress"
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${mysql_database}
      WORDPRESS_DB_USER: ${mysql_user}
      WORDPRESS_DB_PASSWORD:  ${mysql_passwd}
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DOMAIN_CURRENT_SITE: ${word_domain}
    networks:
      - web

networks:
  web: 
    external: true 
volumes:
  db_data:  
