version: '3.8'

services:   
  wordpress:
    image: wordpress:latest # can you place this if you want to use you own custom wp image  
    
    volumes:
      - ./wordpress:/var/www/html
    deploy: 
      replicas: 1 
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=web'
        - "traefik.http.routers.wordpress.rule=PathPrefix(`/`)" 
        - "traefik.http.routers.wordpress.middlewares=wordpress-mw"
        - "traefik.http.middlewares.wordpress-mw.stripprefix.prefixes=/wordpress"
        - "traefik.http.routers.wordpress.service=wordpress" 
        - "traefik.http.routers.wordpress.entrypoints=https"
        - "traefik.http.routers.wordpress.tls.certresolver=myresolver"
        - "traefik.http.services.wordpress.loadbalancer.server.port=80"
        - "traefik.http.services.wordpress.loadBalancer.sticky.cookie=true"
        - "traefik.http.services.wordpress.loadBalancer.sticky.cookie.name=wordpress"
    env_file: ../config.env
    networks:
      - web

networks:
  web: 
    external: true 
volumes:
  db_data:  
  wordpress_data:  
