version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    deploy:  
      replicas: 1 
      placement:
        constraints:
          - node.labels.tipo == wickyflix

volumes:
  node-red-data:
 