version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file: ../config.env
    ports:
      - '3306:3306'
    networks:
      - web  
    volumes:
      - 'mysql-db:/var/lib/mysql'
      - 'mysql-cnf:/etc/mysql/conf.d/my.cnf'
      - 'mysql-sql:/docker-entrypoint-initdb.d'
    deploy: 
    replicas: 1
    placement:
      constraints:
        - node.role==manager 
      
networks:
  web: 
    external: true 
volumes:
  mysql-db: 
  mysql-cnf: 
  mysql-sql: 