version: '3.7'

services:
   redis: 
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    ports:
      - '6379:6379'
    networks:
      - web
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    deploy: 
      replicas: 1
      placement:
        constraints:
          - node.role==manager
 
networks:
  web: 
    external: true  